baseURL = "https://trguduru.github.io/"
languageCode = "en-us"
title = "tguduru's"
theme = "hyde-hyde"

publishDir = "trguduru.github.io"


pygmentsCodefences = true
pygmentsStyle = "pygments"
pygmentOptions = "linenos=table,linenos=inline"

DisqusShortname = "tguduru"
[params]
  #themeColor = "theme-base-09"
  #layoutReverse = true
  description ="thoughts"
  toc = "hugo"
  highlightjs = true
  showcomments = true
  relatedPosts = true
  
## Social Accounts
[params.social]
    github = "trguduru"
    linkedin = "tguduru"
    twitter = "tguduru"
    gravatar = "tguduru"

## Main Menu
[[menu.main]]
    name = "Posts"
    weight = 100
    identifier = "posts"
    url = "/posts/"
[[menu.main]]
    name = "Tags"
    identifier = "tags"
    weight = 300
    url = "/tags"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 300
    url = "/about/"